version: "3.3"
services:
    db:
        container_name: hub_db
        image: mcr.microsoft.com/mssql/server
        environment:
            SA_PASSWORD: "!Abc123++!"
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Express"
        ports:
            - "1433:1433"
        volumes:
            - dbdata:/var/opt/mssql
 
    web:
        container_name: hub_web
        image: tiagodocusse/hub
        depends_on:
            - db
        ports:
            - "8080:80"
        volumes:
            - webdata:/var/opt/hub
            
volumes:
  dbdata:
  webdata:
