version: "3.3"
services:
    db:
        container_name: hub_db
        image: tiagodocusse/hubsql
        environment:
            SA_PASSWORD: "!Abc123++!"
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Express"
        ports:
            - "1401:1433"
        networks:
            - nethub
        volumes:
            - dbdata:/var/opt/mssql
 
    web:
        container_name: hub_web
        image: tiagodocusse/hub
        depends_on:
            - db
        ports:
            - "8080:80"
        networks:
            - nethub
        volumes:
            - webdata:/var/opt/hub
            
networks:
  nethub:

volumes:
  dbdata:
  webdata:
